### ISSUE TITLE
No Quarkus projects were detected in this folder

### ISSUE THREAD

**Issue by gnpace** [xorye/vscode-quarkus#526]
Hello,

I have installed VSCode (Ubuntu 21.10) with the Quarkus extension.

If I open a Quarkus project on VSCode and select **Quarkus: Add extensions to current project** then a tooltip appears saying **No Quarkus projects were detected in this folder**.

If I open a Quarkus project on VSCode and select **Quarkus: debug current Quarkus project** then a tooltip appears saying **No Quarkus projects were detected in this folder**.

What do I need to configure in order to fix the folder detection?

Thanks!

**Comment by rgrunber** [comment]
I'm able to reproduce. Latest version (1.9.0) of vscode-java breaks the currently release version of vscode-quarkus + vscode-microprofile.

**client log**
```
[Trace - 10:12:33 a.m.] Sending response 'microprofile/java/projectLabels - (19)'. Processing request took 10ms
Jul. 22, 2022 10:12:33 A.M. org.eclipse.lsp4mp.ls.java.JavaTextDocuments lambda$getProjectInfo$0
WARNING: Error while getting ProjectLabelInfoEntry (classpath) for 'file:///home/rgrunber/sample-projects/my-quarkus-example/src/main/java/org/example/Utils.java'
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request microprofile/java/projectLabels failed with message: No delegateCommandHandler for microprofile/java/projectLabels
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4mp.ls.commons.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:148)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**server log**
```
!ENTRY org.eclipse.lsp4mp.jdt.core 4 0 2022-07-22 10:11:48.584
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.lsp4mp.jdt.core [83]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.lifecyclemapping.defaults

    at org.eclipse.osgi.container.Module.start(Module.java:463)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY com.redhat.microprofile.jdt.quarkus 4 0 2022-07-22 10:11:48.586
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.redhat.microprofile.jdt.quarkus [84]
  Unresolved requirement: Require-Bundle: org.eclipse.lsp4mp.jdt.core
    -> Bundle-SymbolicName: org.eclipse.lsp4mp.jdt.core; bundle-version="0.4.0.20220324-1704"; singleton:="true"
       org.eclipse.lsp4mp.jdt.core [83]
         Unresolved requirement: Require-Bundle: org.eclipse.m2e.lifecyclemapping.defaults

    at org.eclipse.osgi.container.Module.start(Module.java:463)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

~~My guess is, because JDT-LS had to switch to a Java 17 runtime, the older microprofile.jdt & quarkus.jdt extensions aren't working as expected.~~ . It's the m2e migration. The lsp4mp + quarkus components that get injected into the JDT-LS runtime reference an m2e bundle that no longer exists.

Can you confirm that switching to vscode-java 1.8.0 fixes the issue ? I think we just need to get the release out https://github.com/redhat-developer/vscode-quarkus/issues/504 .

**Comment by gnpace** [comment]
Hello @rgrunber, 
thanks for the quick reply.
Yes, I can confirm that switching to vscode-java 1.8.0 fixes the issue.

Thanks!

**Comment by rgrunber** [comment]
Alternatively, you could also switch to the latest snapshots for vscode-microprofile & vscode-quarkus :
https://download.jboss.org/jbosstools/vscode/snapshots/vscode-microprofile/vscode-microprofile-0.5.0-238.vsix https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/vscode-quarkus-1.11.0-544.vsix

Those folders should contain the latest changes (until we also add pre-release support in the extensions for these), which won't have the issue.

**Comment by rgrunber** [comment]
vscode-microprofile 0.5.0 & vscode-quarkus 1.11.0 should be published now. Let me know if they reolsve the issue when used with vscode-java 1.9.0.

**Comment by fbricon** [comment]
@gnpace can you confirm this is no longer an issue with the latest release please?

**Comment by rgrunber** [comment]
This is no longer an issue. Closing.

**Update** : whoops, thought it was a general inquiry about the issue. I'll leave this open for @gnpace to confirm.

**Comment by gnpace** [comment]
Hi @rgrunber, sorry for the late reply. Yes, I can confirm this is no longer an issue with the latest release.

I've installed the following extensions:
- vscode-microprofile 0.5.0
- vscode-quarkus 1.11.0
- vscode-java 1.9.0

Thanks!
