### ISSUE TITLE
Version 18 release duplicate key issue

### ISSUE THREAD

**Issue by dcentrih** [xorye/vscode-quarkus#822]
After switching to the release version (18) of the plugin today I started getting these errors in my Qute templates.
This happens in a template that uses a PageData wrapper which holds the things I need. 
If the passed argument is a primitive it works fine.

```
[Error - 5:14:15 PM] Request textDocument/inlayHint failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Duplicate key data (attempted merging values ExtendedDataModelParameter [
  key = "data"
  sourceType = "...source"
  dataMethodInvocation = false
] and ExtendedDataModelParameter [
  key = "data"
  sourceType = "...source"
  dataMethodInvocation = false
])
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at com.redhat.qute.parser.template.Template.getParameterDataModel(Template.java:222)
	at com.redhat.qute.parser.template.Template.findInInitialDataModel(Template.java:195)
	at com.redhat.qute.parser.expression.ObjectPart.resolveJavaType(ObjectPart.java:126)
	at com.redhat.qute.project.JavaDataModelCache.resolveJavaType(JavaDataModelCache.java:470)
	at com.redhat.qute.project.JavaDataModelCache.resolveJavaType(JavaDataModelCache.java:362)
	at com.redhat.qute.project.JavaDataModelCache.resolveJavaType(JavaDataModelCache.java:127)
	at com.redhat.qute.project.JavaDataModelCache.resolveJavaType(JavaDataModelCache.java:111)
	at com.redhat.qute.project.QuteProject.resolveJavaType(QuteProject.java:651)
	at com.redhat.qute.services.inlayhint.InlayHintASTVistor.getJavaType(InlayHintASTVistor.java:366)
	at com.redhat.qute.services.inlayhint.InlayHintASTVistor.createJavaTypeInlayHint(InlayHintASTVistor.java:322)
	at com.redhat.qute.services.inlayhint.InlayHintASTVistor.visit(InlayHintASTVistor.java:113)
	at com.redhat.qute.parser.template.sections.ForSection.accept0(ForSection.java:50)
	at com.redhat.qute.parser.template.Node.accept(Node.java:338)
	at com.redhat.qute.parser.template.Node.acceptChildren(Node.java:405)
	at com.redhat.qute.parser.template.sections.IncludeSection.accept0(IncludeSection.java:141)
	at com.redhat.qute.parser.template.Node.accept(Node.java:338)
	at com.redhat.qute.parser.template.Node.acceptChildren(Node.java:405)
	at com.redhat.qute.parser.template.Template.accept0(Template.java:312)
	at com.redhat.qute.parser.template.Node.accept(Node.java:338)
	at com.redhat.qute.services.QuteInlayHint.lambda$getInlayHint$0(QuteInlayHint.java:74)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at com.redhat.qute.services.QuteInlayHint.getInlayHint(QuteInlayHint.java:59)
	at com.redhat.qute.services.QuteLanguageService.getInlayHint(QuteLanguageService.java:216)
	at com.redhat.qute.ls.template.TemplateFileTextDocumentService.lambda$inlayHint$23(TemplateFileTextDocumentService.java:298)
	at com.redhat.qute.ls.commons.ModelTextDocuments.lambda$computeModelAsyncCompose$1(ModelTextDocuments.java:144)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by angelozerr** [comment]
Have you this error with previous version?

**Comment by angelozerr** [comment]
@dcentrih could you share your project please?

**Comment by dcentrih** [comment]
I've been using version 17 till a few days ago. I then switched to the the pre-release version 18 which fixed the qute basePath issue on CheckedTemplate.

The project can be found here: https://github.com/dcentrih/dash-temp

The qute template in question is in templates/pages/index.html

**Comment by angelozerr** [comment]
Thanks @dcentrih !

There is indeed a problem when data model is collected which duplicates `data` parameters:

```
[Trace - 5:15:22 PM] Sending response 'qute/template/projectDataModel - (17)'. Processing request took 11005ms
Result: {
    "templates": [
       ...
        {
            "templateUri": "src/main/resources/templates/pages/index",
            "sourceType": "dash.controller.AppController$Pages",
            "sourceMethod": "index",
            "parameters": [
                {
                    "key": "data",
                    "sourceType": "dash.data.PageData"
                },
                {
                    "key": "data",
                    "sourceType": "dash.data.PageData"
                }
            ]
        }
```

I need to investigate JDT code.

**Comment by angelozerr** [comment]
@dcentrih as your issue was a major problem, we created a new release 1.18.1 which should fix your issue.

**Comment by angelozerr** [comment]
@dcentrih please install the prerelease to enjoy the fix.

**Comment by dcentrih** [comment]
I have tested both version 18.1 and and 18.2 prerelease and both work now.

**Comment by angelozerr** [comment]
Thanks for your feedback. 

Hope you will enjoy with 18.1.
